info:
  description: Spring Cloud Samples
  url: https://github.com/spring-cloud-samples
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
PRE:
    DS:
        CACHEWEBS:
            DB:
                CCBS: jVrabf2Cglql0doU+Ph6ymvZqR3Pq1WsvZgeT1RNAiS4zpqyaR2Tt675MKK/Ih8ae4cJoV7gr59DI6kl7h2V60+DzO7FbHAQ4tM5/AIDv1kyaGUym/iinyedd1Lf+2x/sFZ+hQtHHTL0wAzp08f49A6l3eRY18izxLUrRatIHQxeheUukLweE3cM3Z+Fg2knqnIOX5lnYEjOemqLWOdq2bARfRRcVXkU1Bd5UP8YQYNhqbfoeWdkFdTuhi047YqhTJJgpFmsMFEAPhdozIKlLA==
                ARS: LkIOsQrbI9os8xJxMBqkZFyODGxTTAJaHDP7nlOYdjohiOcXywQdl8W3SAldvRfhF0/tBcBok01mLwiV5j4A+gWz6SxAYcx2E6GDjkp/w/p20Xi9E0lgu5C4XIA36MvndPrgvVf5zh/PUks5cf8/a098RwWo370ldQ3lljT6l8W2+0g+IK0xNzZOG2wOK8JYB3P2f6uvCyPTMGpArbzKTAFSdd4q4kcQMM63AUnz8XkPbDIu3dV4PlnLV7qIk/j1t1lszSRBjNzzEGOT80h3Svn5tbyZqniyDbhmjFnugrE=
                DST: LkIOsQrbI9os8xJxMBqkZFyODGxTTAJaHDP7nlOYdjohiOcXywQdl8W3SAldvRfhF0/tBcBok01mLwiV5j4A+gWz6SxAYcx2E6GDjkp/w/p20Xi9E0lgu5C4XIA36MvndPrgvVf5zh/PUks5cf8/a098RwWo370ldQ3lljT6l8W2+0g+IK0xNzZOG2wOK8JYB3P2f6uvCyPTMGpArbzKTAFSdd4q4kcQMM63AUnz8XkPbDIu3dV4PlnLV7qIk/j1t1lszSRBjNzzEGOT80h3Svn5tbyZqniyDbhmjFnugrE=
                DLR: LkIOsQrbI9os8xJxMBqkZFyODGxTTAJaHDP7nlOYdjohiOcXywQdl8W3SAldvRfhF0/tBcBok01mLwiV5j4A+gWz6SxAYcx2E6GDjkp/w/p20Xi9E0lgu5C4XIA36MvndPrgvVf5zh/PUks5cf8/a098RwWo370ldQ3lljT6l8W2+0g+IK0xNzZOG2wOK8JYB3P2f6uvCyPTMGpArbzKTAFSdd4q4kcQMM63AUnz8XkPbDIu3dV4PlnLV7qIk/j1t1lszSRBjNzzEGOT80h3Svn5tbyZqniyDbhmjFnugrE=
            WS:
                DSCACHENET: miOTgI1ic2MfYfBFL7Jem/6z51tbwKASJR36bdAttCxFVgUA1cvgvde1bKY5TnWmtOwMwdpn7sRY1PX4stXwQgl/xcQaF+mUMVbUDIzyMmE=
