info:
  description: Spring Cloud Samples
  url: https://github.com/spring-cloud-samples
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
PRE:
    DS:
        CACHEWEBS:
            CCBS: jVrabf2Cglql0doU+Ph6ymvZqR3Pq1WsvZgeT1RNAiS4zpqyaR2Tt675MKK/Ih8ae4cJoV7gr59DI6kl7h2V60+DzO7FbHAQ4tM5/AIDv1kyaGUym/iinyedd1Lf+2x/sFZ+hQtHHTL0wAzp08f49A6l3eRY18izxLUrRatIHQxeheUukLweE3cM3Z+Fg2knqnIOX5lnYEjOemqLWOdq2bARfRRcVXkU1Bd5UP8YQYNhqbfoeWdkFdTuhi047YqhTJJgpFmsMFEAPhdozIKlLA==